import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#ffffff",
  },
  contentContainer: {
    flex: 1,
    paddingHorizontal: 28,
    alignItems: "center",
    justifyContent: "space-between",
    paddingTop: 60,
    paddingBottom: 48,
  },
  illustrationContainer: {
    alignItems: "center",
    justifyContent: "center",
    marginTop: 20,
  },
  textGroup: {
    alignItems: "center",
    marginTop: 24,
  },
  title: {
    fontSize: 26,
    fontWeight: "700",
    color: "#000000",
    textAlign: "center",
    marginBottom: 16,
    fontFamily: "System",
  },
  subtitle: {
    fontSize: 14,
    color: "#8a94a6",
    textAlign: "center",
    lineHeight: 22,
    fontWeight: "400",
    fontFamily: "System",
  },
  buttonContainer: {
    width: "100%",
    marginTop: 24,
  },
  button: {
    backgroundColor: "#d90404",
    height: 56,
    borderRadius: 14,
    alignItems: "center",
    justifyContent: "center",
    shadowColor: "#d90404",
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.3,
    shadowRadius: 10,
    elevation: 8,
  },
  buttonText: {
    color: "#ffffff",
    fontSize: 16,
    fontWeight: "700",
  },

  // Success Card Graphic illustration styling
  successGraphicsContainer: {
    alignItems: "center",
    justifyContent: "center",
    width: 280,
    height: 280,
    marginVertical: 20,
    position: "relative",
  },
  glowBackground: {
    width: 220,
    height: 220,
    borderRadius: 110,
    backgroundColor: "#f4f7fc",
    alignItems: "center",
    justifyContent: "center",
    position: "relative",
  },
  blueArc: {
    position: "absolute",
    width: 60,
    height: 60,
    borderRadius: 30,
    borderWidth: 3.5,
    borderColor: "#4ba3f5",
    borderBottomColor: "transparent",
    borderLeftColor: "transparent",
    top: 15,
    right: 15,
    transform: [{ rotate: "15deg" }],
  },
  pinkSquiggle: {
    position: "absolute",
    width: 32,
    height: 32,
    borderRadius: 16,
    borderWidth: 4,
    borderColor: "#ff4a7d",
    borderBottomColor: "transparent",
    borderRightColor: "transparent",
    bottom: 45,
    left: 20,
    transform: [{ rotate: "-35deg" }],
  },
  orangeSquiggle: {
    position: "absolute",
    width: 24,
    height: 24,
    borderRadius: 12,
    borderWidth: 3.5,
    borderColor: "#ff9800",
    borderTopColor: "transparent",
    borderLeftColor: "transparent",
    bottom: 40,
    right: 25,
    transform: [{ rotate: "45deg" }],
  },
  // Dots
  dotBlue1: {
    position: "absolute",
    width: 6,
    height: 6,
    borderRadius: 3,
    backgroundColor: "#4ba3f5",
    top: 50,
    left: 40,
  },
  dotOrange1: {
    position: "absolute",
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: "#ff9800",
    top: 60,
    right: 40,
  },
  dotBlue2: {
    position: "absolute",
    width: 6,
    height: 6,
    borderRadius: 3,
    backgroundColor: "#4ba3f5",
    bottom: 80,
    left: 55,
  },
  dotGrey1: {
    position: "absolute",
    width: 4,
    height: 4,
    borderRadius: 2,
    backgroundColor: "#b0bec5",
    top: 100,
    left: 55,
  },
  dotGrey2: {
    position: "absolute",
    width: 4,
    height: 4,
    borderRadius: 2,
    backgroundColor: "#b0bec5",
    bottom: 100,
    right: 50,
  },
  // White card
  cardContainer: {
    width: 140,
    height: 180,
    borderRadius: 20,
    backgroundColor: "#ffffff",
    padding: 16,
    justifyContent: "space-between",
    shadowColor: "#000000",
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.08,
    shadowRadius: 12,
    elevation: 6,
    position: "relative",
  },
  cardShadowBackground: {
    position: "absolute",
    width: 140,
    height: 180,
    borderRadius: 20,
    backgroundColor: "#cbd5e1",
    opacity: 0.25,
    top: 6,
    left: 6,
  },
  cardTopRightButton: {
    position: "absolute",
    top: 12,
    right: 12,
    width: 24,
    height: 24,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: "#edf2f7",
    backgroundColor: "#ffffff",
    alignItems: "center",
    justifyContent: "center",
  },
  cardTopRightButtonText: {
    fontSize: 10,
    color: "#718096",
    fontWeight: "bold",
    marginLeft: 1,
  },
  cardGreenBadgeContainer: {
    width: 54,
    height: 54,
    borderRadius: 27,
    backgroundColor: "#eafaf1",
    alignItems: "center",
    justifyContent: "center",
    alignSelf: "center",
    marginTop: 24,
  },
  cardGreenBadgeInner: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: "#4cd964",
    alignItems: "center",
    justifyContent: "center",
  },
  cardGreenBadgeText: {
    color: "#ffffff",
    fontSize: 20,
    fontWeight: "bold",
    marginTop: -2,
  },
  cardGreyPill: {
    width: 76,
    height: 10,
    borderRadius: 5,
    backgroundColor: "#626d7e",
    alignSelf: "center",
    marginBottom: 8,
  },
  cardLightBox: {
    width: 108,
    height: 30,
    borderRadius: 8,
    backgroundColor: "#f1f3f7",
    alignSelf: "center",
  },
});
