import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#ffffff",
  },
  scrollContainer: {
    flexGrow: 1,
    paddingHorizontal: 28,
    paddingTop: 80,
    paddingBottom: 32,
  },
  headerContainer: {
    alignItems: "center",
    marginBottom: 16,
  },
  title: {
    fontSize: 28,
    fontWeight: "700",
    color: "#000000",
    marginBottom: 8,
    fontFamily: "System",
  },
  subtitle: {
    fontSize: 14,
    color: "#8a94a6",
    fontWeight: "400",
    fontFamily: "System",
  },
  logoContainer: {
    alignItems: "center",
    justifyContent: "center",
    alignSelf: "center",
  },
  logoImage: {
    width: 74,
    height: 74,
  },
  formContainer: {
    width: "100%",
    marginTop: 10,
  },
  label: {
    fontSize: 14,
    fontWeight: "600",
    color: "#000000",
    marginBottom: 8,
    marginTop: 16,
  },
  inputWrapper: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#f7f8fa",
    borderRadius: 12,
    borderWidth: 1.5,
    borderColor: "transparent",
    paddingHorizontal: 16,
    height: 56,
  },
  inputWrapperFocused: {
    borderColor: "#d90404",
    backgroundColor: "#ffffff",
  },
  textInput: {
    flex: 1,
    color: "#1a1f26",
    fontSize: 15,
    fontWeight: "500",
    height: "100%",
  },
  dropdownSelector: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    backgroundColor: "#f7f8fa",
    borderRadius: 12,
    borderWidth: 1.5,
    borderColor: "transparent",
    paddingHorizontal: 16,
    height: 56,
  },
  dropdownText: {
    flex: 1,
    color: "#1a1f26",
    fontSize: 15,
    fontWeight: "500",
  },
  dropdownPlaceholder: {
    flex: 1,
    color: "#a0aec0",
    fontSize: 15,
    fontWeight: "500",
  },
  chevronContainer: {
    justifyContent: "center",
    alignItems: "center",
    marginRight: 4,
    marginTop: -2,
  },
  chevronArrow: {
    width: 8,
    height: 8,
    borderBottomWidth: 2,
    borderRightWidth: 2,
    borderColor: "#8a94a6",
    transform: [{ rotate: "45deg" }],
  },
  signUpButton: {
    backgroundColor: "#d90404",
    height: 56,
    borderRadius: 14,
    alignItems: "center",
    justifyContent: "center",
    shadowColor: "#d90404",
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.3,
    shadowRadius: 10,
    elevation: 8,
    marginTop: 28,
    marginBottom: 28,
  },
  signUpButtonText: {
    color: "#ffffff",
    fontSize: 16,
    fontWeight: "700",
  },
  separatorContainer: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 28,
  },
  separatorLine: {
    flex: 1,
    height: 1,
    backgroundColor: "#f0f2f5",
  },
  separatorText: {
    fontSize: 13,
    color: "#8a94a6",
    paddingHorizontal: 16,
    fontWeight: "500",
  },
  googleButton: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    height: 56,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: "#edf0f4",
    backgroundColor: "#ffffff",
    marginBottom: 28,
  },
  googleIconContainer: {
    marginRight: 12,
  },
  googleButtonText: {
    fontSize: 16,
    color: "#626d7e",
    fontWeight: "600",
  },
  loginContainer: {
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
    marginTop: 8,
  },
  loginText: {
    fontSize: 14,
    color: "#000000",
    fontWeight: "600",
  },
  loginLink: {
    fontSize: 14,
    color: "#d90404",
    fontWeight: "700",
  },
  // Modal Picker Styles
  modalOverlay: {
    flex: 1,
    backgroundColor: "rgba(0,0,0,0.5)",
    justifyContent: "flex-end",
  },
  modalContent: {
    backgroundColor: "#ffffff",
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    paddingTop: 20,
    paddingBottom: 40,
    paddingHorizontal: 28,
  },
  modalHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 20,
  },
  modalTitle: {
    fontSize: 18,
    fontWeight: "700",
    color: "#000000",
  },
  modalCloseButtonText: {
    fontSize: 15,
    fontWeight: "600",
    color: "#d90404",
  },
  modalOptionItem: {
    paddingVertical: 16,
    borderBottomWidth: 1,
    borderBottomColor: "#f0f2f5",
  },
  modalOptionText: {
    fontSize: 16,
    fontWeight: "500",
    color: "#1a1f26",
  },
  modalOptionTextSelected: {
    color: "#d90404",
    fontWeight: "700",
  },
});
